package com.sample
 import java.util.*;
import javax.swing.JOptionPane;


//Regras de perguntas do paciente
//NOTAS
//
//
rule "paciente tem cirrose"
	salience 100
    when
        $p : Paciente(cirrose == -1);
    then

        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " tem cirrose?", "Cirrose",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);


		if(op==0){
			$p.setCirrose(1);
		}else{
			$p.setCirrose(0);
			$p.setFibroseHipaticaAvançada(0);
			$p.setaAguardarTransplanteHepático(0);
			$p.setEstadio('0');
		}
		update($p);
        
end

rule "child-pugh"
	salience 99
    when
        $p : Paciente(estadio == 'F' && cirrose == 1);
    then
    	 Object[] options = {"A","B","C","Nenhum"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " esta em que estagio de Child-Pugh?", "Child-Pugh",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[3]);
    		
    		
    	switch(op){
    	
    	case 0:
    		$p.setEstadio('A');
    		break;
    	case 1:
			$p.setEstadio('B');
    		break;
    	case 2:
    		$p.setEstadio('C');
    		break;
    	case 3:
    		$p.setEstadio('0');
    		break;
    	};
		update($p);
        
end




rule "paciente tem hepatite B ativa"
	salience 98
    when
        $p : Paciente(hepatite_ativa == -1);
    then
        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " Hepatite B ativa?", "Hepatite B",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);


		if(op==0){
			$p.setHepatite_ativa(1);
		}else{
			$p.setHepatite_ativa(0);
			$p.setVHB(0);
		}
		update($p);
        
end


rule "paciente tem VHB cronico"
	salience 97
    when
        $p : Paciente(VHB == -1 && hepatite_ativa==1 );
    then
        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " é portador cronico de VHB?", "VHB",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
    		
		if(op==0){
			$p.setVHB(1);
		}else{
			$p.setVHB(0);
		}
		update($p);
        
end


rule "paciente com historia de familia de CHC "
	salience 96
    when
        $p : Paciente(historicoCHC == -1);
    then
        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " é tem algum familiar com historico de CHC?", "Historico de Familia",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
    		
		if(op==0){
			$p.setHistoricoCHC(1);
		}else{
			$p.setHistoricoCHC(0);
		}
		update($p);
        
end

rule "paciente tem hepatite cronica C"
	salience 95
    when
        $p : Paciente(HepatiteCronica == -1);
    then
        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " tem Hepatite Crónica C?", "Hepatite Crónica C",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
    		
		if(op==0){
			$p.setHepatiteCronica(1);
		}else{
			$p.setHepatiteCronica(0);
		}
		update($p);
        
end


rule "paciente tem fibrose hepatica avançada "
	salience 94
    when
        $p : Paciente(fibroseHipaticaAvançada == -1);
    then
    	Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " tem Fibrose Hepatica Avançada?", "Fibrose Hepatica Avançada",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
    		
    		
		if(op==0){
			$p.setFibroseHipaticaAvançada(1);
		}else{
			$p.setFibroseHipaticaAvançada(0);
		}
		update($p);
        
end


rule "paciente esta a aguandar transplate hepatico"
	salience 93
    when
        $p : Paciente(aAguardarTransplanteHepático == -1);
    then
    	Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O Paciente " + $p.getNome()+ " esta a aguardar Transplante Hepático?", "Transplante Hepático",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
    		
		if(op==0){
			$p.setaAguardarTransplanteHepático(1);
		}else{
			$p.setaAguardarTransplanteHepático(0);
		}
		update($p);
        
end
/*
rule "fuma/bebe"
	salience 92
	when
		$p : Paciente(fumaBebe == -1);
	then
		System.out.println("o paciente " + $p.getNome()+ " fuma ou bebe?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setFumaBebe(1);
		}else{
			$p.setFumaBebe(0);
		}
		update($p);
end
*/
//ANTES DA ECOGRAFIA



//Regras para ver se o paciente é apto para vigilancia
//NOTAS
//
//
rule "1 regra para determinar se o paciente deve ir para vigilancia"
	salience 80
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==1 && (estadio == 'A' || estadio == 'B'));
    then
		JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " deve ir para Vigilancia!", "Vigilancia",JOptionPane.WARNING_MESSAGE);        
		$p.setAptoParaViginalancia(1);
		update($p); 
end

rule "2 regra para determinar se o paciente deve ir para vigilancia"
	salience 79
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==1 && estadio == 'C' && aAguardarTransplanteHepático ==1 );
    then
		JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " deve ir para Vigilancia!", "Vigilancia",JOptionPane.WARNING_MESSAGE);        
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule "3 regra para determinar se o paciente deve ir para vigilancia"
	salience 78
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==0 && VHB == 1 && (hepatite_ativa == 1 || historicoCHC == 1) );
    then
		JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " deve ir para Vigilancia!", "Vigilancia",JOptionPane.WARNING_MESSAGE);        
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule "4 regra para determinar se o paciente deve ir para vigilancia"
	salience 77
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==0 && HepatiteCronica == 1 && fibroseHipaticaAvançada == 1 );
    then
		JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " deve ir para Vigilancia!", "Vigilancia",JOptionPane.WARNING_MESSAGE);        
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule " o paciente nao deve ir para vigilancia"
	salience 76
    when
        $p : Paciente(aptoParaViginalancia == -1 );
    then
		JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " não deve ir para Vigilancia!", "Vigilancia",JOptionPane.ERROR_MESSAGE);        
        $p.setAptoParaViginalancia(0);
        System.exit(0);
		update($p); 
end

//regras para analizar os nodulos
//NOTAS
//
//Exam 0 = US
//Exam 1 = Repeat US
//Exam 2 = TC e RM
//Exam 3 = TC e RM com equipamento sufisticado
//Exam 4 = biopsy
//Exam 5 = null
//
//o exame 2 e 3 passam na mesma regra, 
//mas o exame 3 passa tambem na regra para saber 
//se o equipamento foi sufisticado

//insert nodulos
rule "Ecografia inicial"
	salience 75
    when
		$p : Paciente(Nnodulos ==-1);
    then
		
    	int result = Integer.parseInt(JOptionPane.showInputDialog(null,"Indique o numero de nodulos encontrados na ecogradia inicial","Ecografia Inicial",JOptionPane.QUESTION_MESSAGE));
		
		if(result<=0){
			JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ "não tem nenhum nodulo, não podemos proseguir", "ERRO",JOptionPane.ERROR_MESSAGE);        
	  		System.exit(0);
		}

		$p.setNnodulos(result);
		
		update($p);
        
end





//dizer tanbem qual o exame a fazer
rule "analise de tamanho e localizacao dos nodulos"
	salience 74
    when
		$p : Paciente(Nnodulos > 0);
		not Nodule();
    then
    	Scanner input = new Scanner(System.in);
    	
    	int n = $p.getNnodulos();
    	
		for(int i=0; i<n; i++){
			Nodule nodulo = new Nodule(i);
    		float t = Float.parseFloat(JOptionPane.showInputDialog(null,"Indique o tamanho do nodulo "+ i +" :","Nodulo " + i,JOptionPane.QUESTION_MESSAGE));
			nodulo.setTamanho(t);
			String loc = JOptionPane.showInputDialog(null,"Indique a localização do nodulo "+ i +" :","Nodulo " + i,JOptionPane.QUESTION_MESSAGE);
			nodulo.setLocal(loc);
			insert(nodulo);
		
		};
        
end

rule "orientar para os exames"
	salience 73
    when
    	$p :Paciente();
		$n : Nodule(exame == -1);
    then
    	if($n.getTamanho()<1){
    		$n.setExame(0);
			JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " necessita de fazer um US", "US",JOptionPane.WARNING_MESSAGE);        
    	}else if($n.getTamanho()>1 && $n.getTamanho()<2){
    	    $n.setExame(3);
    	    JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " necessita de Realizar TC ou RM dinamica com contraste", "TC ou RM dinamica com contraste",JOptionPane.WARNING_MESSAGE);        
    	    
    	}else{
    	    $n.setExame(2);
    	   	JOptionPane.showMessageDialog(null, "O paciente " + $p.getNome()+ " necessita de Realizar TC ou RM dinamica com contraste", "TC ou RM dinamica com contraste",JOptionPane.WARNING_MESSAGE);        
    	   	
    	}
    	update($n)
        
end




//alterar esta para comparar com o tamanho inicial
rule "US"
	salience 71
    when
        $n :Nodule(exame==0)
        not HCC();
    then

    	float t = Float.parseFloat(JOptionPane.showInputDialog(null,"Qual o tamanho do nodulo registado na US " + $n.getId() + " no US ?" + $n.getId(),"US ao Nodulo " + $n.getId(),JOptionPane.QUESTION_MESSAGE));
    	
    	$n.setTamanho(t);
    	if(t<1){
    		$n.setExame(1);
    		JOptionPane.showMessageDialog(null, "Estavel, reptir US daqui a 4 meses", "Resultado da US ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
    		
    	}else if(t>1 &&t<2){
    		$n.setExame(3);//preciso de vereficar se o equipamento é sofisticado
    		JOptionPane.showMessageDialog(null, "Nodulo com " + t + "cm é necessario um CT ou RM Dinamica com contraste \n Recomendado centro de excelencia ",  "Resultado da US ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        

        }else if(t>2){
       	 	$n.setExame(2);
    		JOptionPane.showMessageDialog(null, "Nodulo com " + t + "cm é necessario um CT ou RM Dinamica com contraste", "Resultado da US ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
       	 }
        update($n);
        
end


rule "ct e rm"
	salience 70
    when
        $n :Nodule(exame==2 || exame ==3);
        not HCC();
    then
    
        int nPositives = Integer.parseInt(JOptionPane.showInputDialog(null,"Quantas tecnicas ficaram positivas no nodulo " + $n.getId() + "?(1 ou 2)" + $n.getId(),"CT e RM ao Nodulo " + $n.getId(),JOptionPane.QUESTION_MESSAGE));

		if(nPositives == 0){
			JOptionPane.showMessageDialog(null, "É necessario uma Biopsia !",  "CT e RM ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			
			$n.setExame(4);
		}else if(nPositives==2 || ($n.getExame()==2 && nPositives == 1)){
			JOptionPane.showMessageDialog(null, "É HCC!",  "CT e RM ao Nodulo  " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			$n.setExame(5);
			insert(new HCC());
		}
		update($n);
end


rule "equipamento sofisticado"
	salience 69
    when
        $n :Nodule(exame==3);
        not HCC();
    then
    Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O equipamento usado na realizacao dos exames ao nodulo " + $n.getId() + " era sofisticado ?", "Equipamento sofisticado?",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);

	
		if(op==0){
			JOptionPane.showMessageDialog(null, "É HCC!",  "CT e RM ao Nodulo  " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			$n.setExame(5);
			insert(new HCC());
		}else{
			JOptionPane.showMessageDialog(null, "É necessario uma Biopsia !",  "CT e RM ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			$n.setExame(4);
		}
		update($n);
end
rule "Biopsy"
	salience 68
    when
        $n :Nodule(exame==4);
        not HCC();
    then
        Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O resultado da Biopsia ao nodulo " + $n.getId() + " foi positiva?", "Biopsia ao Nodulo " + $n.getId() ,
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
 
		if(op==0){
			JOptionPane.showMessageDialog(null, "É HCC!",  "Biopsia ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			insert(new HCC());
		}else{
			JOptionPane.showMessageDialog(null, "Resultado inconclusivo, porfavor repita a Ecografia daqui a 4 meses", "Biopsia ao Nodulo " + $n.getId(),JOptionPane.WARNING_MESSAGE);        
			$n.setExame(1);
		}
		update($n);
end

//// CHC
//
// NODULO
rule "CHC"
	salience 60
    when
        exists HCC();
    then
    	JOptionPane.showMessageDialog(null, "Vamos agora avaliar o estádio do CHC!",  "Estadio CHC! ",JOptionPane.WARNING_MESSAGE);        
    
end

rule "PS KARNOFSKY"
	salience 59

    when
    	exists HCC();
        $p : Paciente(PS_KARNOFSKY == -1);
    then
    
    	int result = Integer.parseInt(JOptionPane.showInputDialog(null,
    	"Indique escala de desempenho Karnofsky do paciente:\n\n"	+
    		"100 - Normal, sem queixas e sem ividencia de doenças\n"+
    		"\t90 - Capaz de efectuar tarefas normais, sintomas ou sinais de doença menores \n"+
    	"\t80 - Atividade normal com esforço, alguns sinais ou sintomas de doença\n"+
    	"\t70 - Cuida de si mesmo, mas incapaz de realizar uma atividade normal ou de fazer um trabalho ativo\n"+
    	"\t60 - Requer assistência ocasional, mas é capaz de cuidar da maioria das necessidades pessoais\n"+
    	"\t50 - Requer assistência considerável e cuidados médicos freqüentes\n"+
    	"\t40 - Deficente,requer cuidados e assistência especiais\n"+
    	"\t30 - Deficente sério, a hospitalização é indicada, embora a morte não seja iminente\n"+
    	"\t20 - Muito doente,  hospitalização e cuidados de suporte ativos necessários\n"+
    	"\t10 - Moribundo\n"+
    	"\t0 - Morto",
    	"Escala de desempenho Karnofsky",JOptionPane.QUESTION_MESSAGE));

		if(result>=0 && result<=100){
			$p.setPS_KARNOFSKY(result);;
		}else{
			$p.setPS_KARNOFSKY(-1);
		}
		update($p);
        
end

rule "PS ECOG 0 "
	salience 58

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 89);
    then
		$p.setPS_ECOG(0);
		update($p);
        
end

rule "PS ECOG 1 "
	salience 57

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 69 && PS_KARNOFSKY < 90);
    then
		$p.setPS_ECOG(1);
		update($p);
        
end

rule "PS ECOG 2 "
	salience 56

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 49 && PS_KARNOFSKY < 70);
    then
		$p.setPS_ECOG(2);
		update($p);  
end

rule "PS ECOG 3"
	salience 55

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 29 && PS_KARNOFSKY < 50);
    then
		$p.setPS_ECOG(3);
		update($p);  
end


rule "PS ECOG 4"
	salience 54

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 0 && PS_KARNOFSKY < 30);
    then
		$p.setPS_ECOG(4);
		update($p);  
end



rule "PS ECOG 5"
	salience 53

    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY == 0);
    then
		$p.setPS_ECOG(5);
		update($p);  
end


//Regra para avaliar o N!
//
//

rule "N1"
	salience 52

    when
    	exists HCC(N==-1);// N ainda nao havaliado
   		$h : HCC();
   		exists (Nodule(local=="Visícula") || Nodule(local=="Estomago") || Nodule(local=="Pâncreas") )
    then
    	$h.setN(1);
    	update($h);
end

//Regra para avaliar o M!
//
//

rule "M1"
	salience 51
	
    when
    	exists HCC(M==-1);// M ainda nao havaliado
   		$h : HCC();
   		exists (Nodule(local!="Visícula") && Nodule(local!="Estomago") && Nodule(local!="Pâncreas") )
    then
    	$h.setM(1);
    	update($h);
 
end





//esta regra vai dizer o estagio conforme o PST E o resto



rule "Sera estagio 0?"//feito
	salience 50
    when
    	
    	exists HCC();
    	$h : HCC(stage=='1')
  		$p : Paciente(PS_ECOG==0 && (estadio=='A' || estadio == '0') && Nnodulos==1 ) 
  		$n : Nodule(tamanho<2) //pode ser feito aqui porque so passa na linha de cima de só houver 1 nodulo
    then
    	JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" está no Estadio muito inicial (0)",  "Estadio muito inicial (0)",JOptionPane.WARNING_MESSAGE);        
        $h.setStage('0');
        update($h);
end

rule "Sera estagio A?"//correto agora
	salience 49
	when
    	exists HCC();
    	$h : HCC(stage=='1');
    	$p: Paciente(PS_ECOG==0 &&(estadio=='A' || estadio=='B'|| estadio == '0'));	
    	$ns :	ArrayList(size<=3 && size>=1)
    			from collect (Nodule(tamanho<=3))
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" está no Estadio Inicial (A)",  "Estadio  Inicial (A)",JOptionPane.WARNING_MESSAGE);        
    
        $h.setStage('A');
        $p.setPressaoPortal(-1);
        update($h);

end



rule "Sera estagio B?" //feito
	salience 48
    when
    	exists HCC();
    	$h : HCC(stage=='1')
    	$p : Paciente(PS_ECOG==0 && (estadio=='A' || estadio=='B'|| estadio == '0') && Nnodulos>3)
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" está no Estadio Intermédio(B)",  "Estadio Intermédio(B)",JOptionPane.WARNING_MESSAGE);        
   
        $h.setStage('B');
        update($h);
end
rule "Sera estagio C?" //feito missing erp«cao portal
	salience 47
    when
    	exists HCC();
    	$h : HCC(stage=='1' && (N==1 || M==1))
    	$p : Paciente((PS_ECOG==1 || PS_ECOG==2) && (estadio=='A' || estadio=='B'|| estadio == '0'))    	
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" está no Estadio Avançado (C)",  "Estadio Avançado (C)",JOptionPane.WARNING_MESSAGE);        
        $h.setStage('C');
        update($h);
end
rule "Sera estagio D?"//feito
	salience 46
    when
    	exists HCC();
    	$h : HCC(stage=='1')
    	$p : Paciente(PS_ECOG > 2 && estadio == 'C')
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" está no  Estadio Terminal (D)",  " Estadio Terminal (D)",JOptionPane.WARNING_MESSAGE);  
        $h.setStage('D');
        update($h);

end


// REGRAS ESTAGIO 0
//
//

rule "Tratamento Estadio 0"//feito
	salience 45
    when
       $h : HCC(stage=='0');
       $p: Paciente(Tratamento=="VAZIO");
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" tem um Carcinoma que deve ser removido o mais rápido possível.",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
        $p.setTratamento("Remoção de Carciona");
        update($p);
end

// REGRAS ESTAGIO A
//
//
//Perguntas complementares a esta regra
rule "pressão portal"//feito
	salience 44
	when 
		$h : HCC(stage=='A');
		$p : Paciente(Nnodulos==1 && PressaoPortal==-1 && Tratamento == "VAZIO");
	then
		Object[] options = {"Sim","Não"};
		int op = JOptionPane.showOptionDialog(null, "O pacinete "+$p.getNome()+" tem pressão portal aumentada?", "Pressão Portal",
    		JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
    		null,options,options[1]);
	
		
		if(op==0){
			$p.setPressaoPortal(1);
			$p.setDoencasAssociadas(-1);
		}else{
			$p.setPressaoPortal(0);
		}
		update($p);
end

rule "Tratamento Resseçao" //testar
	salience 42
	when 
		$h : HCC(stage=='A');
		$p : Paciente(Nnodulos==1 && PressaoPortal==0 && Tratamento == "VAZIO");
	then
			JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" de uma ressesao",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
			$p.setTratamento("Resseçâo");

			update($p);
end

rule "Doenças associadas" //testar
	salience 41//isto só acontece se a pressao aumentar (=1) porque senao as regras anteriores disparam e nao cega aqui
	when //trust me
		$h : HCC(stage=='A');
		$p : Paciente(DoencasAssociadas == -1 && (hepatite_ativa ==1 || hepatiteCronica  ==1 || VHB == 1) && Tratamento == "VAZIO")//pq o vazio altera nas anteriores
	then
			$p.setDoencasAssociadas(1);
			update($p);
end


rule "Tratamento Transplante" //testar
	salience 40
	when 
		$h : HCC(stage=='A');
		$p : Paciente( Tratamento == "VAZIO" && ( DoencasAssociadas==-1||DoencasAssociadas==0 ))
		
	then
			JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" precisa de um Transplante",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
			$p.setTratamento("Transplante");

			update($p);
end


rule "Tratamento Ablaçao percutanea" //testar
	salience 39
	when 
		$h : HCC(stage=='A');
		$p : Paciente( Tratamento == "VAZIO" && DoencasAssociadas==1)
	then
				JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" precisa de uma Ablacação percutânea",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
				$p.setTratamento("Ablacação percutânea");
			

			update($p);
		
end






// REGRAS ESTAGIO B
//
//
rule "Tratamento Quimioembolizacao"
	salience 35
    when
       $h : HCC(stage=='B');
       $p: Paciente(Tratamento == "VAZIO");    
    
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" precisa de  Quimioembolização",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
        $p.setTratamento("Quimioembolização");
        update($p);
end

// REGRAS ESTAGIO C
//
//
rule "tratamento Sorafenib"
	salience 30
    when
       $h : HCC(stage=='C');
       $p: Paciente(Tratamento == "VAZIO");    
    
    then
    	JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" precisa de  Sorafenib",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
        $p.setTratamento("Sorafenib");
        update($p);
end

// REGRAS ESTAGIO D
//
//
rule "Tratamento Sintomático"
	salience 20
    when
       $h : HCC(stage=='D');
       $p: Paciente(Tratamento == "VAZIO");    
    
    then
        JOptionPane.showMessageDialog(null, "O paciente "+$p.getNome()+" precisa de  Sintomático",  "Tratamento",JOptionPane.WARNING_MESSAGE);  
        $p.setTratamento("Sintomático");
        update($p);
end



