package com.sample
 import java.util.*;


//Regras de perguntas do paciente
//NOTAS
//
//
rule "paciente tem cirrose"
	salience 100
    when
        $p : Paciente(cirrose == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " tem cirrose?");
		System.out.print("» ");
		
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setCirrose(1);
		}else{
			$p.setCirrose(0);
			$p.setFibroseHipaticaAvançada(0);
			$p.setaAguardarTransplanteHepático(0);
		}
		update($p);
        
end

rule "child-pugh"
	salience 99
    when
        $p : Paciente(estadio == 'F' && cirrose == 1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " esta em que estagio de Child-Pugh?(A,B,C, 0 nunhum)");
		System.out.print("» ");
		
		Scanner input = new Scanner(System.in);
    	char result =  input.next().charAt(0);
		if(result == 'a' || result == 'A'){
			$p.setEstadio('A');
		}else if(result == 'b' || result == 'B'){
			$p.setEstadio('B');
		}else if(result == 'c' || result == 'C'){
			$p.setEstadio('C');
		}else{
			$p.setEstadio('0');
		}
		update($p);
        
end




rule "paciente tem hepatite B ativa"
	salience 98
    when
        $p : Paciente(hepatite_ativa == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " tem hepatite B activa?");
		System.out.print("» ");
		
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setHepatite_ativa(1);
		}else{
			$p.setHepatite_ativa(0);
			$p.setVHB(0);
		}
		update($p);
        
end


rule "paciente tem VHB cronico"
	salience 97
    when
        $p : Paciente(VHB == -1 && hepatite_ativa==1 );
    then
    	System.out.println("o paciente " + $p.getNome()+ " é portador cronico de VHB?");
		System.out.print("» ");
		
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setVHB(1);
		}else{
			$p.setVHB(0);
		}
		update($p);
        
end


rule "paciente com historia de familia de CHC "
	salience 96
    when
        $p : Paciente(historicoCHC == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " tem algum familiar com historico de CHC?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setHistoricoCHC(1);
		}else{
			$p.setHistoricoCHC(0);
		}
		update($p);
        
end

rule "paciente tem hepatite cronica C"
	salience 95
    when
        $p : Paciente(HepatiteCronica == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " tem hepatite crónica C?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setHepatiteCronica(1);
		}else{
			$p.setHepatiteCronica(0);
		}
		update($p);
        
end


rule "paciente tem fibrose hepatica avançada "
	salience 94
    when
        $p : Paciente(fibroseHipaticaAvançada == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " tem fibrose hepatica avancada?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setFibroseHipaticaAvançada(1);
		}else{
			$p.setFibroseHipaticaAvançada(0);
		}
		update($p);
        
end


rule "paciente esta a aguandar transplate hepatico"
	salience 93
    when
        $p : Paciente(aAguardarTransplanteHepático == -1);
    then
    	System.out.println("o paciente " + $p.getNome()+ " esta a aguandar transplate hepatico?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setaAguardarTransplanteHepático(1);
		}else{
			$p.setaAguardarTransplanteHepático(0);
		}
		update($p);
        
end
/*
rule "fuma/bebe"
	salience 92
	when
		$p : Paciente(fumaBebe == -1);
	then
		System.out.println("o paciente " + $p.getNome()+ " fuma ou bebe?");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			$p.setFumaBebe(1);
		}else{
			$p.setFumaBebe(0);
		}
		update($p);
end
*/
//ANTES DA ECOGRAFIA



//Regras para ver se o paciente é apto para vigilancia
//NOTAS
//
//
rule "1 regra para determinar se o paciente deve ir para vigilancia"
	salience 80
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==1 && (estadio == 'A' || estadio == 'B'));
    then
        System.out.println("o "+$p.getNome() + " deve ir para vigilancia");
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule "2 regra para determinar se o paciente deve ir para vigilancia"
	salience 79
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==1 && estadio == 'C' && aAguardarTransplanteHepático ==1 );
    then
        System.out.println("o "+$p.getNome() + " deve ir para vigilancia");
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule "3 regra para determinar se o paciente deve ir para vigilancia"
	salience 78
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==0 && VHB == 1 && (hepatite_ativa == 1 || historicoCHC == 1) );
    then
        System.out.println("o "+$p.getNome() + " deve ir para vigilancia");
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule "4 regra para determinar se o paciente deve ir para vigilancia"
	salience 77
    when
        $p : Paciente(aptoParaViginalancia == -1 && cirrose==0 && HepatiteCronica == 1 && fibroseHipaticaAvançada == 1 );
    then
        System.out.println("o "+$p.getNome() + " deve ir para vigilancia");
        $p.setAptoParaViginalancia(1);
		update($p); 
end

rule " o paciente nao deve ir para vigilancia"
	salience 76
    when
        $p : Paciente(aptoParaViginalancia == -1 );
    then
        System.out.println("o "+$p.getNome() + " não deve ir para vigilancia, obrigado");
        $p.setAptoParaViginalancia(0);
        System.exit(0);
		update($p); 
end

//regras para analizar os nodulos
//NOTAS
//
//Exam 0 = US
//Exam 1 = Repeat US
//Exam 2 = TC e RM
//Exam 3 = TC e RM com equipamento sufisticado
//Exam 4 = biopsy
//Exam 5 = null
//
//o exame 2 e 3 passam na mesma regra, 
//mas o exame 3 passa tambem na regra para saber 
//se o equipamento foi sufisticado

rule "US"
	salience 75
    when
        $n :Nodule(exame==0)
        not HCC();
    then
        System.out.println("Qual o tamanho do nodulo " + $n.getId() + " na ecografia ?");
    	Scanner input = new Scanner(System.in);
    	Float t = input.nextFloat();
    	$n.setTamanho(t);
    	if(t<1){
    		$n.setExame(1);
    		System.out.println("Estavel, reptir ecografia daqui a 4 meses");
    	}else if(t>1 &&t<2){
    		$n.setExame(3);//preciso de vereficar se o equipamento é sofisticado
        	System.out.println("Nodulo com" + t + "cm é necessario um CT ou RM Dinamica com contraste");
        	System.out.println("Recomendado centro de excelencia");
        }else if(t>2){
       	 	$n.setExame(2);
       	 	System.out.println("Nodulo com" + t + "cm é necessario um CT ou RM Dinamica com contraste");
       	 }
        update($n);
        
end


rule "ct e rm"
	salience 70
    when
        $n :Nodule(exame==2 || exame ==3);
        not HCC();
    then
        System.out.println("Quantas tecnicas ficaram positivas no nodulo " + $n.getId() + "?(1 ou 2)");
    	Scanner input = new Scanner(System.in);
    	int nPositives = input.nextInt();
		if(nPositives == 0){
			System.out.println("É necessario uma Biopsia !");
			$n.setExame(4);
		}else if(nPositives>=2 || ($n.getExame() ==2  && nPositives >= 1)){
			System.out.println("É HCC!");
			$n.setExame(5);
			insert(new HCC());
		}
		update($n);
end


rule "equipamento sofisticado"
	salience 69
    when
        $n :Nodule(exame==3);
        not HCC();
    then
        System.out.println("o equipamento usado na realizacao dos exames ao nodulo " + $n.getId() + " era sofisticado ?");
    
    	Scanner input = new Scanner(System.in);
    	String result = input.nextLine();	
	
		if(result.equalsIgnoreCase("sim")){
			System.out.println("É HCC!");
			$n.setExame(5);
			insert(new HCC());
		}else{
			System.out.println("É necessario uma Biopsia !");
			$n.setExame(4);
		}
		update($n);
end
rule "Biopsy"
	salience 60
    when
        $n :Nodule(exame==4);
        not HCC();
    then
        System.out.println("O resultado da Biopsia ao nodulo " + $n.getId() + " foi positiva?");
    	Scanner input = new Scanner(System.in);
    	String result = input.nextLine();
		if(result.equalsIgnoreCase("sim")){
			System.out.println("É HCC!");
			insert(new HCC());
		}else{
			System.out.println("Resultado inconclusivo ,porfavor repita a Ecografia daqui a 4 meses");
			$n.setExame(1);
		}
		update($n);
end

//Determinar o estagio de HCH
rule "HCC-stage"
	salience 50
    when
       exists $h : HCC();
    then
        System.out.println("Toi?");
end



//este é mais perciso
rule "PS KARNOFSKY"
    when
        $p : Paciente(PS_KARNOFSKY == -1);
    then
    	System.out.println("Indique escala de desempenho Karnofsky do paciente " + $p.getNome()+ " ?");
		System.out.println("100 - Normal, sem queixas e sem ividencia de doenças");
		System.out.println("90 - Capaz de efectuar tarefas normais, sintomas ou sinais de doença menores ");
		System.out.println("80 - Atividade normal com esforço, alguns sinais ou sintomas de doença");
		System.out.println("70 - Cuida de si mesmo, mas incapaz de realizar uma atividade normal ou de fazer um trabalho ativo");
		System.out.println("60 - Requer assistência ocasional, mas é capaz de cuidar da maioria das necessidades pessoais");
		System.out.println("50 - Requer assistência considerável e cuidados médicos freqüentes");
		System.out.println("40 - Deficente,requer cuidados e assistência especiais");
		System.out.println("30 - Deficente sério, a hospitalização é indicada, embora a morte não seja iminente");
		System.out.println("20 - Muito doente,  hospitalização e cuidados de suporte ativos necessários");
		System.out.println("10 - Moribundo");
		System.out.println("0 - Morto");
		System.out.print("» ");
		Scanner input = new Scanner(System.in);
    	int result =  input.nextInt();
		if(result>=0 && result<=100){
			$p.setPS_KARNOFSKY(result);;
		}else{
			$p.setaAguardarTransplanteHepático(-1);
		}
		update($p);
        
end

rule "PS ECOG 0 "
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 89);
    then
		$p.setPS_ECOG(0);
		update($p);
        
end

rule "PS ECOG 1 "
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 69 && PS_KARNOFSKY < 90);
    then
		$p.setPS_ECOG(1);
		update($p);
        
end

rule "PS ECOG 2 "
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 49 && PS_KARNOFSKY < 70);
    then
		$p.setPS_ECOG(2);
		update($p);  
end

rule "PS ECOG 3"
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 29 && PS_KARNOFSKY < 50);
    then
		$p.setPS_ECOG(3);
		update($p);  
end


rule "PS ECOG 4"
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY > 0 && PS_KARNOFSKY < 30);
    then
		$p.setPS_ECOG(4);
		update($p);  
end


rule "PS ECOG 5"
    when
        $p : Paciente(PS_ECOG==-1 && PS_KARNOFSKY == 0);
    then
		$p.setPS_ECOG(5);
		update($p);  
end
